Neos:
  Flow:
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            matchingStatusCodes: [ 404, 410 ]
            options:
              viewClassName: Neos\FluidAdaptor\View\TemplateView
              templatePathAndFilename: 'resource://MOC.NotFound/Private/Templates/404.html'
              variables:
                path: '404.html' # skip suffix if unset
